### ISSUE TITLE
Spec-only entity shouldn't have status-only fields

### ISSUE THREAD

**Issue by Emulebest** [nutanix/papiea#490]
Such case is found in test examples in papiea-engine tests
```
Location:
  type: object
  title: X/Y Location
  description: Stores an XY location of something
  x-papiea-entity: spec-only
  required:
    - x
    - y
  properties:
    x:
      type: number
    y:
      type: number
    z:
      type: number
      x-papiea: status-only
    v:
      type: object
      properties:
        e:
          type: number
        d:
          type: number
```
